# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c32bd7a7f8d17baaef9d7ef32d1e1465fab4dd4fd3b326e14e0ed43e0a6765845f9fc6cf413beefabc09a7c665ef80669cbdac6d4f9fcb5fe3c5382e249b3cd9

test:
  secret_key_base: e4302fb57e8d0e8c363fc83f6e2b73eae4804d93ea65db53c745f6797b4977c784310c6c95300dba62c4fc26c4424407bd240bcc388b45fa4efac3ff06cac151

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
